/*
 * TreasuryInitialPage.java
 *
 * Created on February 11, 2011, 7:37 AM
 */

package cashreceipt.ui;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  ms
 */
@StyleSheet
public class CashBreakdownPage extends javax.swing.JPanel {
    
    /** Creates new form TreasuryInitialPage */
    public CashBreakdownPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();

        setOpaque(false);
        xDataTable1.setHandler("listHandler");
        xDataTable1.setImmediate(true);
        xDataTable1.setName("selection");

        formPanel3.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xNumberField3.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xNumberField3.setCaption("Total Cash Breakdown");
        xNumberField3.setCaptionWidth(125);
        xNumberField3.setDepends(new String[] {"selection"});
        xNumberField3.setFieldType(java.math.BigDecimal.class);
        xNumberField3.setFont(new java.awt.Font("Courier New", 1, 14));
        xNumberField3.setName("totalBreakdown");
        xNumberField3.setOpaque(false);
        xNumberField3.setPattern("#,##0.00");
        xNumberField3.setPreferredSize(new java.awt.Dimension(0, 30));
        xNumberField3.setReadonly(true);
        formPanel3.add(xNumberField3);

        xNumberField4.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xNumberField4.setCaption("Total Amount");
        xNumberField4.setCaptionWidth(125);
        xNumberField4.setDepends(new String[] {"selectedR"});
        xNumberField4.setFieldType(java.math.BigDecimal.class);
        xNumberField4.setFont(new java.awt.Font("Courier New", 1, 14));
        xNumberField4.setForeground(new java.awt.Color(204, 0, 0));
        xNumberField4.setName("totalAmount");
        xNumberField4.setOpaque(false);
        xNumberField4.setPattern("#,##0.00");
        xNumberField4.setPreferredSize(new java.awt.Dimension(0, 30));
        xNumberField4.setReadonly(true);
        formPanel3.add(xNumberField4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, xDataTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(xDataTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    // End of variables declaration//GEN-END:variables
    
}
