/*
 * TreasuryInitialPage.java
 *
 * Created on February 11, 2011, 7:37 AM
 */

package cashreceipt.ui;

import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  ms
 */
@Template(PopupTemplate.class)
public class CheckPaymentOptionPage extends javax.swing.JPanel {
    
    /** Creates new form TreasuryInitialPage */
    public CheckPaymentOptionPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();

        setPreferredSize(new java.awt.Dimension(451, 232));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel1.setText("CHECK PAYMENT");
        jLabel1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());

        formPanel1.setCaptionWidth(120);
        xTextField2.setCaption("Bank");
        xTextField2.setFont(new java.awt.Font("Arial", 0, 18));
        xTextField2.setName("bank");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 27));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xTextField1.setCaption("Check No");
        xTextField1.setFont(new java.awt.Font("Arial", 0, 18));
        xTextField1.setName("checkno");
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 25));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xDateField1.setCaption("Check Date");
        xDateField1.setFont(new java.awt.Font("Arial", 0, 18));
        xDateField1.setName("checkdate");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 27));
        xDateField1.setRequired(true);
        formPanel1.add(xDateField1);

        xNumberField3.setCaption("Amount");
        xNumberField3.setDepends(new String[] {"amount"});
        xNumberField3.setFieldType(java.math.BigDecimal.class);
        xNumberField3.setFont(new java.awt.Font("Arial", 0, 18));
        xNumberField3.setName("amount");
        xNumberField3.setPreferredSize(new java.awt.Dimension(150, 25));
        xNumberField3.setRequired(true);
        formPanel1.add(xNumberField3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 395, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(17, 17, 17)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JLabel jLabel1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
    
}
