/*
 * ProfessionalBackground.java
 *
 * Created on August 23, 2011, 10:20 AM
 */

package loan.ui;

/**
 *
 * @author  user
 */
public class ProfessionalBackground extends javax.swing.JPanel {
    
    /** Creates new form ProfessionalBackground */
    public ProfessionalBackground() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xTextField55 = new com.rameses.rcp.control.XTextField();
        xTextField56 = new com.rameses.rcp.control.XTextField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xTextArea8 = new com.rameses.rcp.control.XTextArea();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        formPanel4.setCaptionWidth(100);
        xTextField55.setCaption("School Attended");
        xTextField55.setName("entity.schoolAttended");
        xTextField55.setPreferredSize(new java.awt.Dimension(166, 19));
        xTextField55.setRequired(true);
        formPanel4.add(xTextField55);

        xTextField56.setCaption("Profession");
        xTextField56.setName("entity.profession");
        xTextField56.setPreferredSize(new java.awt.Dimension(166, 19));
        xTextField56.setRequired(true);
        formPanel4.add(xTextField56);

        xDateField2.setCaption("Date Graduated");
        xDateField2.setName("entity.dateGraduated");
        xDateField2.setPreferredSize(new java.awt.Dimension(166, 19));
        xDateField2.setUseDatePickerModel(true);
        formPanel4.add(xDateField2);

        xTextArea8.setColumns(20);
        xTextArea8.setRows(5);
        xTextArea8.setCaption("Others");
        xTextArea8.setHint("Specify your specifications here.");
        xTextArea8.setName("entity.othersSpecs");
        xTextArea8.setRequired(true);
        formPanel4.add(xTextArea8);

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 9, Short.MAX_VALUE)
        );

        xActionBar1.setName("formActions");
        xActionBar1.setUseToolBar(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, xSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextArea xTextArea8;
    private com.rameses.rcp.control.XTextField xTextField55;
    private com.rameses.rcp.control.XTextField xTextField56;
    // End of variables declaration//GEN-END:variables
    
}
