/*
 * RealPropertyForm.java
 *
 * Created on February 9, 2011, 9:42 AM
 */

package loan.ui.asset;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.util.TemplateProvider;
import loan.ui.*;
/**
 *
 * @author  rameses
 */
@Template(AssetPopupTemplate.class)
@StyleSheet("loan/ui/ApplicationForm.style")
public class ApplianceForm extends javax.swing.JPanel {
    
    /** Creates new form RealPropertyForm */
    public ApplianceForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Appliance");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(135);
        xTextField5.setCaption("Subject");
        xTextField5.setName("asset.subject");
        xTextField5.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField5.setRequired(true);
        formPanel1.add(xTextField5);

        xTextField1.setCaption("Kind");
        xTextField1.setName("asset.type");
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField2.setCaption("Brand");
        xTextField2.setName("asset.brand");
        xTextField2.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xDateField1.setCaption("Date Acquired");
        xDateField1.setName("asset.dateAcquired");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xDateField1.setUseDatePickerModel(true);
        formPanel1.add(xDateField1);

        xTextField4.setCaption("Year Model");
        xTextField4.setName("asset.model");
        xTextField4.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField4.setRequired(true);
        formPanel1.add(xTextField4);

        xTextField3.setCaption("Serial");
        xTextField3.setName("asset.serial");
        xTextField3.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        xNumberField1.setCaption("Market/Appraised value");
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("asset.appraisedvalue");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xNumberField1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 75));
        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("asset.remarks");
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        formPanel1.add(jScrollPane1);

        xNumberField3.setCaption("No. of photo");
        xNumberField3.setFieldType(java.math.BigInteger.class);
        xNumberField3.setName("photonum");
        xNumberField3.setPreferredSize(new java.awt.Dimension(60, 18));
        xNumberField3.setReadonly(true);
        formPanel1.add(xNumberField3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
    
}
