/*
 * RealPropertyForm.java
 *
 * Created on February 9, 2011, 9:42 AM
 */

package loan.ui.asset;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.util.TemplateProvider;
import loan.ui.*;
/**
 *
 * @author  rameses
 */
@Template(AssetPopupTemplate.class)
@StyleSheet("loan/ui/ApplicationForm.style")
public class ORCRLookup extends javax.swing.JPanel {
    
    /** Creates new form RealPropertyForm */
    public ORCRLookup() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xNumberField28 = new com.rameses.rcp.control.XNumberField();
        xNumberField29 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("OR/CR");
        formPanel2.setBorder(xTitledBorder1);
        formPanel2.setCaptionWidth(130);
        formPanel2.setPreferredSize(new java.awt.Dimension(400, 240));
        formPanel2.setShowCaption(false);
        xTextField13.setCaption("CR No.");
        xTextField13.setDepends(new String[] {"asset.hasORCR"});
        xTextField13.setName("asset.crno");
        xTextField13.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField13.setRequired(true);
        formPanel2.add(xTextField13);

        xTextField10.setCaption("Fuel");
        xTextField10.setDepends(new String[] {"asset.hasORCR"});
        xTextField10.setName("asset.fuel");
        xTextField10.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField10.setRequired(true);
        formPanel2.add(xTextField10);

        xTextField11.setCaption("Denomination");
        xTextField11.setDepends(new String[] {"asset.hasORCR"});
        xTextField11.setName("asset.denomination");
        xTextField11.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField11.setRequired(true);
        formPanel2.add(xTextField11);

        xTextField12.setCaption("Series");
        xTextField12.setDepends(new String[] {"asset.hasORCR"});
        xTextField12.setName("asset.series");
        xTextField12.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField12.setRequired(true);
        formPanel2.add(xTextField12);

        xNumberField28.setCaption("Piston Displacement");
        xNumberField28.setDepends(new String[] {"asset.hasORCR"});
        xNumberField28.setFieldType(Integer.class);
        xNumberField28.setName("asset.pistondisplacement");
        xNumberField28.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField28.setRequired(true);
        formPanel2.add(xNumberField28);

        xNumberField29.setCaption("No. of Cylinders");
        xNumberField29.setDepends(new String[] {"asset.hasORCR"});
        xNumberField29.setFieldType(Integer.class);
        xNumberField29.setName("asset.noofcylinders");
        xNumberField29.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField29.setRequired(true);
        formPanel2.add(xNumberField29);

        xNumberField4.setCaption("Net WT.");
        xNumberField4.setDepends(new String[] {"asset.hasORCR"});
        xNumberField4.setFieldType(java.math.BigDecimal.class);
        xNumberField4.setName("asset.netwt");
        xNumberField4.setPattern("#,##0.00");
        xNumberField4.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField4.setRequired(true);
        formPanel2.add(xNumberField4);

        xNumberField2.setCaption("Gross WT.");
        xNumberField2.setDepends(new String[] {"asset.hasORCR"});
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setName("asset.grosswt");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField2.setRequired(true);
        formPanel2.add(xNumberField2);

        xNumberField6.setCaption("Net Capacity");
        xNumberField6.setDepends(new String[] {"asset.hasORCR"});
        xNumberField6.setFieldType(java.math.BigDecimal.class);
        xNumberField6.setName("asset.netcap");
        xNumberField6.setPattern("#,##0.00");
        xNumberField6.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField6.setRequired(true);
        formPanel2.add(xNumberField6);

        xNumberField5.setCaption("Shipping WT.");
        xNumberField5.setDepends(new String[] {"asset.hasORCR"});
        xNumberField5.setFieldType(java.math.BigDecimal.class);
        xNumberField5.setName("asset.shipwt");
        xNumberField5.setPattern("#,##0.00");
        xNumberField5.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField5.setRequired(true);
        formPanel2.add(xNumberField5);

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 321, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1, Short.MAX_VALUE)
        );

        xButton1.setText("Add");
        xButton1.setName("add");

        xButton2.setText("Cancel");
        xButton2.setName("_close");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(xSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField28;
    private com.rameses.rcp.control.XNumberField xNumberField29;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    // End of variables declaration//GEN-END:variables
    
}
