/*
 * RealPropertyForm.java
 *
 * Created on February 9, 2011, 9:42 AM
 */

package loan.ui.asset;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import loan.ui.*;
/**
 *
 * @author  rameses
 */
@Template(AssetPopupTemplate.class)
@StyleSheet("loan/ui/ApplicationForm.style")
public class OtherCollateralForm extends javax.swing.JPanel {
    
    /** Creates new form RealPropertyForm */
    public OtherCollateralForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Other Collaterals");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(135);
        xLabel1.setForeground(new java.awt.Color(255, 51, 51));
        xLabel1.setText("Please fill out the information below if any:");
        xLabel1.setCaption("use the check box to determine the client");
        xLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        xLabel1.setShowCaption(false);
        formPanel1.add(xLabel1);

        xTextField8.setCaption("Subject");
        xTextField8.setName("asset.subject");
        xTextField8.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField8.setRequired(true);
        formPanel1.add(xTextField8);

        xTextField1.setCaption("Registered Name");
        xTextField1.setName("asset.registeredName");
        xTextField1.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xComboBox1.setCaption("Use");
        xComboBox1.setItems("use");
        xComboBox1.setName("asset.use");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("Mode of Acquisition");
        xComboBox2.setItems("modeOfAcquisition");
        xComboBox2.setName("asset.modeOfAcquisition");
        xComboBox2.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox2);

        xDateField1.setCaption("Date Acquired");
        xDateField1.setName("asset.dateAcquired");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xDateField1.setUseDatePickerModel(true);
        formPanel1.add(xDateField1);

        xNumberField1.setCaption("Market/Appraised value");
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("asset.appraisedvalue");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xNumberField1);

        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("asset.remarks");
        xTextArea1.setRequired(true);
        formPanel1.add(xTextArea1);

        xNumberField3.setCaption("No. of photo");
        xNumberField3.setFieldType(java.math.BigInteger.class);
        xNumberField3.setName("photonum");
        xNumberField3.setPreferredSize(new java.awt.Dimension(60, 18));
        xNumberField3.setReadonly(true);
        formPanel1.add(xNumberField3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField8;
    // End of variables declaration//GEN-END:variables
    
}
