/*
 * PhotoPage.java
 *
 * Created on February 9, 2011, 2:48 PM
 */
package loan.ui.asset;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  rameses
 */

@StyleSheet
@Template(PhotoPreviewTplPage.class)
public class PhotoPreviewImage extends javax.swing.JPanel {
    
    /** Creates new form PhotoPage */
    public PhotoPreviewImage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xImageViewer1 = new com.rameses.rcp.control.XImageViewer();

        xImageViewer1.setAdvanced(true);
        xImageViewer1.setDynamic(true);
        xImageViewer1.setName("photoView");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xImageViewer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xImageViewer1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XImageViewer xImageViewer1;
    // End of variables declaration//GEN-END:variables
    
}
