/*
 * RealPropertyForm.java
 *
 * Created on February 9, 2011, 9:42 AM
 */

package loan.ui.asset;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import loan.ui.*;

/**
 *
 * @author  rameses
 */
@Template(AssetPopupTemplate.class)
public class RealPropertyForm extends javax.swing.JPanel {
    
    /** Creates new form RealPropertyForm */
    public RealPropertyForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();

        formPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Real Property");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(140);
        xTextField3.setCaption("Subject");
        xTextField3.setName("asset.subject");
        xTextField3.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);
        xTextField3.setBounds(146, 215, 250, 19);

        xTextField1.setCaption("Land/Building");
        xTextField1.setName("asset.rpu");
        xTextField1.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);
        xTextField1.setBounds(0, 0, 250, 19);

        xComboBox3.setCaption("Classification");
        xComboBox3.setItems("classification");
        xComboBox3.setName("asset.classification");
        xComboBox3.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox3);
        xComboBox3.setBounds(170, 270, 150, 22);

        xTextField4.setCaption("Location");
        xTextField4.setName("asset.location");
        xTextField4.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField4.setRequired(true);
        formPanel1.add(xTextField4);
        xTextField4.setBounds(0, 0, 250, 19);

        formPanel2.setCaptionWidth(140);
        formPanel2.setOrientation("HORIZONTAL");
        formPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel2.setPreferredSize(new java.awt.Dimension(402, 24));
        formPanel2.setShowCaption(false);
        xNumberField2.setCaption("Area");
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setName("asset.area");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(100, 19));
        formPanel2.add(xNumberField2);

        xComboBox1.setAllowNull(false);
        xComboBox1.setItems("itemUM");
        xComboBox1.setName("asset.uom");
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 19));
        xComboBox1.setShowCaption(false);
        formPanel2.add(xComboBox1);

        formPanel1.add(formPanel2);
        formPanel2.setBounds(0, 0, 402, 24);

        xNumberField4.setCaption("Zonal Value");
        xNumberField4.setFieldType(java.math.BigDecimal.class);
        xNumberField4.setName("asset.zonalvalue");
        xNumberField4.setPattern("#,##0.00");
        xNumberField4.setPreferredSize(new java.awt.Dimension(100, 19));
        formPanel1.add(xNumberField4);
        xNumberField4.setBounds(0, 0, 100, 19);

        xTextField2.setCaption("Registered Name");
        xTextField2.setName("asset.registeredName");
        xTextField2.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);
        xTextField2.setBounds(0, 0, 250, 19);

        xComboBox2.setCaption("Mode of Acquisition");
        xComboBox2.setItems("modeOfAcquisition");
        xComboBox2.setName("asset.modeOfAcquisition");
        xComboBox2.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox2);
        xComboBox2.setBounds(170, 270, 150, 22);

        xNumberField1.setCaption("Market/Appraised value");
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("asset.appraisedvalue");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xNumberField1);
        xNumberField1.setBounds(0, 0, 150, 19);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 75));
        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("asset.remarks");
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        formPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(144, 160, 250, 75);

        xNumberField3.setCaption("No. of photo");
        xNumberField3.setFieldType(java.math.BigInteger.class);
        xNumberField3.setName("photonum");
        xNumberField3.setPreferredSize(new java.awt.Dimension(60, 18));
        xNumberField3.setReadonly(true);
        formPanel1.add(xNumberField3);
        xNumberField3.setBounds(0, 0, 60, 18);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 409, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    // End of variables declaration//GEN-END:variables
    
}
