/*
 * RealPropertyForm.java
 *
 * Created on February 9, 2011, 9:42 AM
 */

package loan.ui.asset;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import loan.ui.*;
/**
 *
 * @author  rameses
 */
@Template(AssetPopupTemplate.class)
@StyleSheet("loan/ui/ApplicationForm.style")
public class VehiclesForm2 extends javax.swing.JPanel {
    
    /** Creates new form RealPropertyForm */
    public VehiclesForm2() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xNumberField28 = new com.rameses.rcp.control.XNumberField();
        xNumberField29 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Vehicle");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(135);
        xTextField8.setCaption("Subject");
        xTextField8.setName("asset.subject");
        xTextField8.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField8.setRequired(true);
        formPanel1.add(xTextField8);

        xTextField1.setCaption("Make");
        xTextField1.setName("asset.make");
        xTextField1.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField2.setCaption("Model");
        xTextField2.setName("asset.model");
        xTextField2.setPreferredSize(new java.awt.Dimension(250, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xTextField3.setCaption("Body Type");
        xTextField3.setName("asset.type");
        xTextField3.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        xComboBox1.setCaption("Use");
        xComboBox1.setItems("vehicleList");
        xComboBox1.setName("asset.use");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox1);

        xDateField1.setCaption("Date Acquired");
        xDateField1.setName("asset.dateAcquired");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xDateField1.setUseDatePickerModel(true);
        formPanel1.add(xDateField1);

        xTextField9.setCaption("Registered Name");
        xTextField9.setName("asset.registeredName");
        xTextField9.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField9.setRequired(true);
        formPanel1.add(xTextField9);

        xTextField7.setCaption("Registration no.");
        xTextField7.setName("asset.regno");
        xTextField7.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField7.setRequired(true);
        formPanel1.add(xTextField7);

        xTextField5.setCaption("Chassis no.");
        xTextField5.setName("asset.chassisno");
        xTextField5.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField5.setRequired(true);
        formPanel1.add(xTextField5);

        xTextField6.setCaption("Plate no.");
        xTextField6.setName("asset.plateno");
        xTextField6.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField6.setRequired(true);
        formPanel1.add(xTextField6);

        xTextField4.setCaption("Engine");
        xTextField4.setName("asset.engineno");
        xTextField4.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField4.setRequired(true);
        formPanel1.add(xTextField4);

        xTextField11.setCaption("Denomination");
        xTextField11.setDepends(new String[] {"isORCR"});
        xTextField11.setName("asset.denomination");
        xTextField11.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField11.setRequired(true);
        formPanel1.add(xTextField11);

        xTextField10.setCaption("Fuel");
        xTextField10.setDepends(new String[] {"isORCR"});
        xTextField10.setName("asset.fuel");
        xTextField10.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField10.setRequired(true);
        formPanel1.add(xTextField10);

        xTextField12.setCaption("Series");
        xTextField12.setDepends(new String[] {"isORCR"});
        xTextField12.setName("asset.series");
        xTextField12.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField12.setRequired(true);
        formPanel1.add(xTextField12);

        xNumberField28.setCaption("Piston Displacement");
        xNumberField28.setDepends(new String[] {"isORCR"});
        xNumberField28.setFieldType(Integer.class);
        xNumberField28.setName("asset.pistondisplacement");
        xNumberField28.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField28.setRequired(true);
        formPanel1.add(xNumberField28);

        xNumberField29.setCaption("No. of Cylinders");
        xNumberField29.setDepends(new String[] {"isORCR"});
        xNumberField29.setFieldType(Integer.class);
        xNumberField29.setName("asset.noofcylinders");
        xNumberField29.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField29.setRequired(true);
        formPanel1.add(xNumberField29);

        xNumberField4.setCaption("Net WT.");
        xNumberField4.setFieldType(java.math.BigDecimal.class);
        xNumberField4.setName("asset.netwt");
        xNumberField4.setPattern("#,##0.00");
        xNumberField4.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xNumberField4);

        xNumberField2.setCaption("Gross WT.");
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setName("asset.grosswt");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xNumberField2);

        xNumberField6.setCaption("Net Capacity");
        xNumberField6.setFieldType(java.math.BigDecimal.class);
        xNumberField6.setName("asset.netcap");
        xNumberField6.setPattern("#,##0.00");
        xNumberField6.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xNumberField6);

        xNumberField5.setCaption("Shipping WT.");
        xNumberField5.setFieldType(java.math.BigDecimal.class);
        xNumberField5.setName("asset.shipwt");
        xNumberField5.setPattern("#,##0.00");
        xNumberField5.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xNumberField5);

        xNumberField1.setCaption("Market/Appraised value");
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("asset.appraisedvalue");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xNumberField1);

        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("asset.remarks");
        xTextArea1.setRequired(true);
        formPanel1.add(xTextArea1);

        xNumberField3.setCaption("No. of photo");
        xNumberField3.setFieldType(java.math.BigInteger.class);
        xNumberField3.setName("photonum");
        xNumberField3.setPreferredSize(new java.awt.Dimension(60, 18));
        xNumberField3.setReadonly(true);
        formPanel1.add(xNumberField3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField28;
    private com.rameses.rcp.control.XNumberField xNumberField29;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
    
}
