/*
 * ResidencyPage.java
 *
 * Created on September 26, 2011, 9:24 AM
 */

package shared.custom.residency;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */
@StyleSheet()
public class ResidencyPage extends javax.swing.JPanel {
    
    /** Creates new form ResidencyPage */
    public ResidencyPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        setOpaque(false);

        formPanel1.setCaptionWidth(90);
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Type");
        xComboBox1.setImmediate(true);
        xComboBox1.setItemsObject(new String[]{"OWNED", "LIVING WITH", "COMPANY-OWNED", "RENTED", "FREE USE", "MORTGAGE BANK", "RIGHTS", "SQUATTERS"});
        xComboBox1.setName("context.type");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setAllowNull(false);
        xComboBox2.setCaption("Rent Type");
        xComboBox2.setDepends(new String[] {"context.type"});
        xComboBox2.setItemsObject(new String[]{"W/ CONTRACT", "W/O CONTRACT"});
        xComboBox2.setName("context.renttype");
        xComboBox2.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xNumberField1.setCaption("Rent Amount");
        xNumberField1.setDepends(new String[] {"context.type"});
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("context.rentamount");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xNumberField1.setRequired(true);
        formPanel1.add(xNumberField1);

        xDateField1.setCaption("Since");
        xDateField1.setDepends(new String[] {"context.type"});
        xDateField1.setName("context.since");
        xDateField1.setPreferredSize(new java.awt.Dimension(152, 18));
        xDateField1.setUseDatePickerModel(true);
        formPanel1.add(xDateField1);

        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("context.remarks");
        formPanel1.add(xTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 251, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
