/*
 * ScriptAnalyzerPage.java
 *
 * Created on January 29, 2011, 5:18 PM
 */

package dev.ui;

import java.awt.BorderLayout;

/**
 *
 * @author  ms
 */
public class ScriptSvcEditorPage extends javax.swing.JPanel {
    
    /** Creates new form ScriptAnalyzerPage */
    public ScriptSvcEditorPage() {
        initComponents();
        
        GroovyScriptEditor gse = new GroovyScriptEditor();        
        gse.setName("service.content");
        remove( xEditorPane1 );
        add( gse, BorderLayout.CENTER );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        toolbar = new javax.swing.JToolBar();
        xButton3 = new com.rameses.rcp.control.XButton();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        xEditorPane1 = new com.rameses.rcp.control.XEditorPane();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(585, 400));
        toolbar.setFloatable(false);
        xButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/ui/icons/save.png")));
        xButton3.setMnemonic('s');
        xButton3.setText("Save");
        xButton3.setAccelerator("ctrl S");
        xButton3.setName("save");
        toolbar.add(xButton3);

        xButton1.setText("Refresh");
        xButton1.setAccelerator("ctrl R");
        xButton1.setName("open");
        toolbar.add(xButton1);

        xButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/ui/icons/run.png")));
        xButton2.setMnemonic('r');
        xButton2.setText("Flush Script");
        xButton2.setAccelerator("ctrl R");
        xButton2.setName("flush");
        toolbar.add(xButton2);

        add(toolbar, java.awt.BorderLayout.NORTH);

        xEditorPane1.setEditable(true);
        xEditorPane1.setContentType("text/java");
        xEditorPane1.setName("service.content");
        jScrollPane1.setViewportView(xEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar toolbar;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XEditorPane xEditorPane1;
    // End of variables declaration//GEN-END:variables
    
}
