/*
 * DisbursementDataCapturePage.java
 *
 * Created on February 27, 2011, 1:05 PM
 */

package loantreasury.disbursement;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */

@StyleSheet
public class DisbursementDataCapturePage extends javax.swing.JPanel {
    
    /**
     * Creates new form DisbursementDataCapturePage
     */
    public DisbursementDataCapturePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xActionTextField1 = new com.rameses.rcp.control.XActionTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xTextField3 = new com.rameses.rcp.control.XTextField();

        xActionBar1.setName("formActions");

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Check Disbursement Data Capture");
        jPanel1.setBorder(xTitledBorder1);

        formPanel1.setCaptionWidth(100);
        formPanel1.setPadding(new java.awt.Insets(5, 0, 5, 5));
        xActionTextField1.setText("borrowername");
        xActionTextField1.setActionName("lookupBorrower");
        xActionTextField1.setCaption("Borrower");
        xActionTextField1.setName("borrowername");
        xActionTextField1.setPreferredSize(new java.awt.Dimension(200, 19));
        xActionTextField1.setRequired(true);
        formPanel1.add(xActionTextField1);

        xTextField2.setCaption("Application No.");
        xTextField2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xTextField2.setName("entity.appno");
        xTextField2.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField2.setReadonly(true);
        formPanel1.add(xTextField2);

        xNumberField1.setCaption("Loan Amount");
        xNumberField1.setFieldType(java.math.BigDecimal.class
        );
        xNumberField1.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField1.setName("entity.loanAmount");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xNumberField1.setReadonly(true);
        formPanel1.add(xNumberField1);

        xTextField5.setCaption("Account No.");
        xTextField5.setName("entity.acctno");
        xTextField5.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField5.setRequired(true);
        formPanel1.add(xTextField5);

        xTextField1.setCaption("Bank");
        xTextField1.setDepends(new String[] {"entity.bankacct"});
        xTextField1.setName("entity.bankname");
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField4.setCaption("Check no");
        xTextField4.setDepends(new String[] {"entity.bankacct"});
        xTextField4.setName("entity.checkno");
        xTextField4.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField4.setRequired(true);
        formPanel1.add(xTextField4);

        xDateField1.setCaption("Date");
        xDateField1.setName("entity.checkdate");
        xDateField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xDateField1.setRequired(true);
        xDateField1.setUseDatePickerModel(true);
        formPanel1.add(xDateField1);

        xNumberField2.setCaption("Check Amount");
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setName("entity.checkamount");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(150, 19));
        xNumberField2.setRequired(true);
        formPanel1.add(xNumberField2);

        xTextField3.setCaption("Particular");
        xTextField3.setName("entity.particulars");
        xTextField3.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XActionTextField xActionTextField1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
    
}
