/*
 * CivilStatusPage.java
 *
 * Created on September 26, 2011, 9:24 AM
 */

package shared.custom.lot;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */
@StyleSheet()
public class CivilStatusPage extends javax.swing.JPanel {
    
    /**
     * Creates new form CivilStatusPage
     */
    public CivilStatusPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        setOpaque(false);

        formPanel1.setCaptionWidth(90);
        formPanel1.setCellpadding(new java.awt.Insets(0, 0, 0, 10));
        formPanel1.setOrientation("HORIZONTAL");
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Type");
        xComboBox1.setImmediate(true);
        xComboBox1.setItemsObject(new String[]{"SINGLE", "MARRIED", "COUPLE", "WIDOW", "SEPARATED", "OTHERS"});
        xComboBox1.setName("context.type");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox1.setRequired(true);
        xComboBox1.setShowCaption(false);
        formPanel1.add(xComboBox1);

        xNumberField1.setCaption("Year(s)");
        xNumberField1.setCaptionWidth(60);
        xNumberField1.setDepends(new String[] {"context.type"});
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("context.year");
        formPanel1.add(xNumberField1);

        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setCaptionWidth(62);
        xTextArea1.setName("context.remarks");
        formPanel2.add(xTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
