/*
 * CheckingForm.java
 *
 * Created on August 30, 2011, 4:53 PM
 */

package loan.bankAccnts;

/**
 *
 * @author  Amancio Family
 */
public class CheckingForm extends javax.swing.JPanel {
    
    /** Creates new form CheckingForm */
    public CheckingForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xTextField55 = new com.rameses.rcp.control.XTextField();
        xTextField56 = new com.rameses.rcp.control.XTextField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xTextArea8 = new com.rameses.rcp.control.XTextArea();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Check Account");
        formPanel4.setBorder(xTitledBorder1);
        formPanel4.setCaptionWidth(100);
        xTextField55.setCaption("Bank Name");
        xTextField55.setName("entity.bankName");
        xTextField55.setPreferredSize(new java.awt.Dimension(166, 19));
        xTextField55.setRequired(true);
        formPanel4.add(xTextField55);

        xTextField56.setCaption("Branch");
        xTextField56.setName("entity.branch");
        xTextField56.setPreferredSize(new java.awt.Dimension(166, 19));
        xTextField56.setRequired(true);
        formPanel4.add(xTextField56);

        xComboBox2.setCaption("Kinds of Check");
        xComboBox2.setItems("checkingList");
        xComboBox2.setName("entity.kindOfCheck");
        xComboBox2.setPreferredSize(new java.awt.Dimension(165, 22));
        xComboBox2.setRequired(true);
        formPanel4.add(xComboBox2);

        xComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "entity.status" }));
        xComboBox3.setCaption("Status");
        xComboBox3.setItems("statusList");
        xComboBox3.setName("entity.status");
        xComboBox3.setPreferredSize(new java.awt.Dimension(165, 22));
        xComboBox3.setRequired(true);
        formPanel4.add(xComboBox3);

        xTextArea8.setColumns(20);
        xTextArea8.setRows(5);
        xTextArea8.setCaption("Others");
        xTextArea8.setHint("Specify your specifications here.");
        xTextArea8.setName("entity.othersSpecs");
        xTextArea8.setRequired(true);
        formPanel4.add(xTextArea8);

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 304, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );

        xActionBar1.setName("formActions");
        xActionBar1.setUseToolBar(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextArea xTextArea8;
    private com.rameses.rcp.control.XTextField xTextField55;
    private com.rameses.rcp.control.XTextField xTextField56;
    // End of variables declaration//GEN-END:variables
    
}
