/*
 * RouteForm.java
 *
 * Created on February 17, 2011, 9:54 AM
 */

package route.ui;
import com.rameses.rcp.ui.annotations.StyleSheet;

@StyleSheet
public class RouteForm extends javax.swing.JPanel {
    
    /**
     * Creates new form RouteForm
     */
    public RouteForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar3 = new com.rameses.rcp.control.XActionBar();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();

        xActionBar3.setName("formActions");

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Route Entry");
        formPanel2.setBorder(xTitledBorder1);
        formPanel2.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.FLOW);
        formPanel2.setPadding(new java.awt.Insets(10, 10, 10, 10));
        formPanel2.setPreferredSize(new java.awt.Dimension(0, 196));
        xLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xLabel1.setCaption("Route Code");
        xLabel1.setName("entity.code");
        xLabel1.setPreferredSize(new java.awt.Dimension(120, 25));
        formPanel2.add(xLabel1);

        xTextField5.setCaption("Description");
        xTextField5.setName("entity.description");
        xTextField5.setPreferredSize(new java.awt.Dimension(350, 25));
        xTextField5.setRequired(true);
        formPanel2.add(xTextField5);

        xTextField4.setCaption("Area");
        xTextField4.setName("entity.area");
        xTextField4.setPreferredSize(new java.awt.Dimension(350, 25));
        xTextField4.setRequired(true);
        formPanel2.add(xTextField4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 369, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XActionBar xActionBar3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
    
}
