/*
 * BusinessOccupancyPage.java
 *
 * Created on September 26, 2011, 9:24 AM
 */

package shared.custom.business;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */
@StyleSheet()
public class BusinessTypePage extends javax.swing.JPanel {
    
    /**
     * Creates new form BusinessOccupancyPage
     */
    public BusinessTypePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xNumberField7 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xTextArea3 = new com.rameses.rcp.control.XTextArea();

        setOpaque(false);

        formPanel1.setCaptionWidth(110);
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Type");
        xComboBox1.setEmptyText("Select Type");
        xComboBox1.setImmediate(true);
        xComboBox1.setItemsObject(new String[]{"SARI-SARI", "CARENDERIA", "OPERATOR", "OTHERS"});
        xComboBox1.setName("context.type");
        xComboBox1.setPreferredSize(new java.awt.Dimension(167, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setAllowNull(false);
        xComboBox2.setCaption("Stall Size/P.O Size");
        xComboBox2.setDepends(new String[] {"context.type"});
        xComboBox2.setEmptyText("Select Stall Size");
        xComboBox2.setImmediate(true);
        xComboBox2.setItemsObject(new String[]{"0.5 x 0.5 = 3T", "1 x 1 = 5T", "1 x 0.5 = 3T-5T", "1 0.5 x 1 = 5T-15T" , "1.5 x 1.5 = 15T-20T", "1 x 2.5 = 15T-20T", "2 x 1 = 5T-15T", "2 x 1.5 = '15T-20T", "2 x 2 = 20T-25T", "2.5 x 1.5 = 20T-40T", "2.5 x 2 = 25T-30T", "2.5 x 2.5 = 30-40T", "3 x 1 = 30T-50T", "3 x 2 = 40T-60T", "3 x 3 = 60T-70T", "3.5 x 3 = 70T-80T", "3 x 4 = 75T-80T", "4 x 1.5 = 50T-70T", "4 x 4 = 50T-80T-100T", "5 x 3 = 50T-80T-100T"});
        xComboBox2.setName("context.stallsize");
        xComboBox2.setPreferredSize(new java.awt.Dimension(167, 22));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xNumberField1.setToolTipText("No. of tables");
        xNumberField1.setCaption("# of. Tables");
        xNumberField1.setDepends(new String[] {"context.type"});
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("context.nooftables");
        xNumberField1.setPreferredSize(new java.awt.Dimension(167, 18));
        xNumberField1.setRequired(true);
        formPanel1.add(xNumberField1);

        xNumberField3.setToolTipText("No. of Chairs");
        xNumberField3.setCaption("# of. Chair");
        xNumberField3.setDepends(new String[] {"context.type"});
        xNumberField3.setFieldType(Integer.class);
        xNumberField3.setName("context.noofchair");
        xNumberField3.setPreferredSize(new java.awt.Dimension(167, 18));
        xNumberField3.setRequired(true);
        formPanel1.add(xNumberField3);

        xNumberField4.setToolTipText("No. of Counter Type");
        xNumberField4.setCaption("# of. Counter Type");
        xNumberField4.setDepends(new String[] {"context.type"});
        xNumberField4.setFieldType(Integer.class);
        xNumberField4.setName("context.noofcountertype");
        xNumberField4.setPreferredSize(new java.awt.Dimension(167, 18));
        xNumberField4.setRequired(true);
        formPanel1.add(xNumberField4);

        xTextArea2.setColumns(20);
        xTextArea2.setRows(5);
        xTextArea2.setCaption("Kind/Size");
        xTextArea2.setDepends(new String[] {"context.type"});
        xTextArea2.setHint("Specify the kind/size plasticware used");
        xTextArea2.setName("context.kind");
        xTextArea2.setRequired(true);
        formPanel1.add(xTextArea2);

        xNumberField5.setToolTipText("No. of Units");
        xNumberField5.setCaption("# of. Units");
        xNumberField5.setDepends(new String[] {"context.type"});
        xNumberField5.setFieldType(Integer.class);
        xNumberField5.setName("context.noofunits");
        xNumberField5.setPreferredSize(new java.awt.Dimension(167, 18));
        xNumberField5.setRequired(true);
        formPanel1.add(xNumberField5);

        xNumberField7.setToolTipText("No. of Seating Capacity");
        xNumberField7.setCaption("# of. Seating Cap.");
        xNumberField7.setDepends(new String[] {"context.type"});
        xNumberField7.setFieldType(Integer.class);
        xNumberField7.setName("context.seatingcap");
        xNumberField7.setPreferredSize(new java.awt.Dimension(167, 18));
        xNumberField7.setRequired(true);
        formPanel1.add(xNumberField7);

        xNumberField2.setForeground(new java.awt.Color(255, 51, 51));
        xNumberField2.setToolTipText("Boundary Fee");
        xNumberField2.setCaption("Boundary Fee");
        xNumberField2.setDepends(new String[] {"context.type"});
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setFont(new java.awt.Font("Arial", 1, 11));
        xNumberField2.setName("context.boundaryfee");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(167, 18));
        xNumberField2.setRequired(true);
        formPanel1.add(xNumberField2);

        xTextArea3.setColumns(20);
        xTextArea3.setRows(5);
        xTextArea3.setCaption("Remarks");
        xTextArea3.setDepends(new String[] {"context.type"});
        xTextArea3.setHint("Specify the kind/size plasticware used");
        xTextArea3.setName("context.remarks");
        xTextArea3.setRequired(true);
        formPanel1.add(xTextArea3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField7;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    private com.rameses.rcp.control.XTextArea xTextArea3;
    // End of variables declaration//GEN-END:variables
    
}
