/*
 * BusinessHours.java
 *
 * Created on September 26, 2011, 9:24 AM
 */

package shared.custom.business;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */
@StyleSheet()
public class BusinessHours extends javax.swing.JPanel {
    
    /**
     * Creates new form BusinessHours
     */
    public BusinessHours() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xTextField3 = new com.rameses.rcp.control.XTextField();

        setOpaque(false);

        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("From");
        xComboBox1.setImmediate(true);
        xComboBox1.setItemsObject(new String[]{"24/7", "1 AM", " 2AM", " 3AM", " 4AM", " 5AM", " 6AM", " 7AM", " 8AM", " 9AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM", "12 AM"});
        xComboBox1.setName("context.businessHoursFrom");
        xComboBox1.setPreferredSize(new java.awt.Dimension(167, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setAllowNull(false);
        xComboBox2.setCaption("To");
        xComboBox2.setImmediate(true);
        xComboBox2.setItemsObject(new String[]{"24/7", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM", "12 AM"});
        xComboBox2.setName("context.businessHoursTo");
        xComboBox2.setPreferredSize(new java.awt.Dimension(167, 22));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xTextField3.setCaption("Days Open");
        xTextField3.setDepends(new String[] {"context.type"});
        xTextField3.setName("context.daysOpen");
        xTextField3.setPreferredSize(new java.awt.Dimension(167, 18));
        xTextField3.setRequired(true);
        xTextField3.setToolTipText("Since");
        formPanel1.add(xTextField3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
