/*
 * QuickLaunchToolBar.java
 *
 * Created on November 2, 2010, 5:04 PM
 */

package system.tools.ui;

/**
 *
 * @author  ms
 */
public class QuickLaunchBar extends javax.swing.JPanel {
    
    /** Creates new form QuickLaunchToolBar */
    public QuickLaunchBar() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xButton1 = new com.rameses.rcp.control.XButton();
        xActionTextField1 = new com.rameses.rcp.control.XActionTextField();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        setPreferredSize(new java.awt.Dimension(207, 24));
        xButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/images/home.png")));
        xButton1.setCaption("");
        xButton1.setContentAreaFilled(false);
        xButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        add(xButton1, java.awt.BorderLayout.WEST);

        xActionTextField1.setEditable(false);
        xActionTextField1.setActionName("launch");
        xActionTextField1.setEnabled(false);
        xActionTextField1.setName("key");
        xActionTextField1.setReadonly(true);
        add(xActionTextField1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XActionTextField xActionTextField1;
    private com.rameses.rcp.control.XButton xButton1;
    // End of variables declaration//GEN-END:variables
    
}
